
name = "mindful-balance-adhd-coaching"
compatibility_date = "2025-03-25"
account_id = "1d881509c2679aa8b5023f278c2ea238"
main = "dist/worker.js"

[observability]
enabled = true

[assets]
directory = "./dist"
