
name = "cindy-romanzo-coaching"
compatibility_date = "2025-03-25"
account_id = "1d881509c2679aa8b5023f278c2ea238"

[observability]
enabled = true

[assets]
directory = "./dist"

[build]
command = "npm run build"
